#!/usr/bin/env python3
from autonomous_recovery_test_utils import test_liver_manager_public_post_reader_facing

test_liver_manager_public_post_reader_facing()
print('PASS test_liver_manager_public_post_reader_facing.py')
