#!/usr/bin/env python3
from autonomous_recovery_test_utils import test_scheduled_workflows_schedule_event_runs_apply

test_scheduled_workflows_schedule_event_runs_apply()
print('PASS test_scheduled_workflows_schedule_event_runs_apply.py')
