#!/usr/bin/env python3
from autonomous_recovery_test_utils import test_liver_manager_workflow_schedule_enabled

test_liver_manager_workflow_schedule_enabled()
print('PASS test_liver_manager_workflow_schedule_enabled.py')
