#!/usr/bin/env python3
from autonomous_recovery_test_utils import test_scheduled_workflows_prepare_only_until_activation

test_scheduled_workflows_prepare_only_until_activation()
print('PASS test_scheduled_workflows_apply_on_schedule.py')
