from autonomous_recovery_test_utils import test_process_threads_queue_picks_ready_text_only

test_process_threads_queue_picks_ready_text_only()
print("PASS test_process_threads_queue_picks_ready_text_only.py")
